### ISSUE TITLE
Frontend Não funciona

### ISSUE THREAD

**Issue by iuryzito** [carloshomar/appdelivery#43]
o frontend não está rodando.

**Comment by carloshomar** [comment]
Olá tudo bem? Você consegue me fornecer mais detalhes do que está acontecendo, por favor!

**Comment by iuryzito** [comment]
O Frontend da aplicação não está rodando! Fica só com uma tela preta

**Comment by iuryzito** [comment]
![imagem_2024-07-02_111332504](https://github.com/carloshomar/appdelivery/assets/162537009/37d93593-ec2c-47e4-85dc-b7c69e1b3ec8)

**Comment by carloshomar** [comment]
Por favor, conseguiria verificar se a versão do node está na versão 20 ou superior, utilizando o comando node -v.

Caso esteja correta, apague a node_modules e limpe o cache do npm utilizando `npm cache clean --force`.

**Comment by iuryzito** [comment]
opa irmão, consegue me ajudar a instalar esse projeto na minha VPS? estou disposto a te pagar.

(99) 99139-5512   -----------  ME CHAMA NO WHATSAPP, aí tu só se identifica que é do projeto
@eu.iury ------------------- ME CHAMA NO INSTAGRAM, aí tu só se identifica que é do projeto

**Comment by carloshomar** [comment]
Olá, podemos conversar sim! Mas aproveitei para subir uma modificação onde agora é possível rodar todos os frontends via Docker. Já estava devendo essa parte há bastante tempo. Acabei de subir esse [Pull Request](https://github.com/carloshomar/appdelivery/pull/46/files) para a main.

É só baixar as modificações e seguir essas instruções abaixo, que estão presentes no README.MD:

<img width="878" alt="image" src="https://github.com/carloshomar/appdelivery/assets/161836226/73845786-063f-472c-8e65-d834e9b75478">

Vou fechar o ticket, caso não consiga, me envie um chat via Discord: **anypercent_**
