### ISSUE TITLE
Consigo instalar no windows?

### ISSUE THREAD

**Issue by iuryzito** [carloshomar/appdelivery#45]
consigo instalar tua aplicação direto no meu windows?

**Comment by carloshomar** [comment]
Olá, podemos conversar sim! Mas aproveitei para subir uma modificação onde agora é possível rodar todos os frontends via Docker. Já estava devendo essa parte há bastante tempo. Acabei de subir esse [Pull Request](https://github.com/carloshomar/appdelivery/pull/46/files) para a main.

É só baixar as modificações e seguir essas instruções abaixo, que estão presentes no README.MD:

<img width="878" alt="image" src="https://github.com/carloshomar/appdelivery/assets/161836226/73845786-063f-472c-8e65-d834e9b75478">

Vou fechar o ticket, caso não consiga, me envie um chat via Discord: **anypercent_**
