### ISSUE TITLE
ERRO NO ARQUIVO docker-compose DO FRONTEND

### ISSUE THREAD

**Issue by iuryzito** [carloshomar/appdelivery#47]
yaml: line 8: found character that cannot start any token

ao tentar rodar o comando do arquivo do frontend, é retornado o seguinte erro acima.

te mandei uma solicitação de amizade no discord me aceita lá pra gente conversar sobre esse projeto.

**Comment by carloshomar** [comment]
Esse erro é dado devido a caracteres especiais no Usuario ou senha do expo, presente no docker compose.
